version: '3.3'

services:
  lms_db:
    hostname: lms_db
    image: mysql:8.0
    #command: mysqld --general-log=1 --general-log-file=/var/log/mysql/general-log.log
    container_name: lms_db
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    volumes:
      - lms_db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root!
      MYSQL_DATABASE: lms 
      MYSQL_USER: lms
      MYSQL_PASSWORD: Password1!
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 10s
      retries: 3





  clportal_db:
    hostname: clportal_db
    container_name: clportal_db 
    image: mysql:8.0
    volumes:
      - clportal_db_data:/var/lib/mysql 
    restart: always
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: cloudportaldb
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 10s
      retries: 3






  lms:
    hostname: lms
    container_name: lms
    depends_on:
      - lms_db
    image: thalesgroupsm/sentinel_ldk_rte:latest
    restart: always
    volumes:
      - type: bind
        source: ./hasplm.ini
        target: /etc/hasplm/hasplm.ini
      - type: bind
        source: ./haspvlib_x86_64_37515.so
        target: /var/hasplm/haspvlib_x86_64_37515.so
    environment:
      HASPLM_DATABASE: mysql
      HASPLM_DATABASE_MYSQL_HOST: lms_db 
      HASPLM_DATABASE_MYSQL_USER: root
      HASPLM_DATABASE_MYSQL_PASSWORD: root!
      HASPLM_DATABASE_MYSQL_PORT: 3306
    healthcheck:
      test: ["CMD", "curl", "-X GET", "http://127.0.0.1:1947/sentinel/ldk/v1/healthz"] 
      interval: 50s
      timeout: 10s
      retries: 3
    ports:
      - "1947:1947"
      # - "80:1947"



  clportal:
    hostname: clportal
    container_name: clportal
    depends_on:
      - lms
      - clportal_db
      - lms_db
    image: thalesgroupsm/sentinel_ldk_cloudportal:latest
    restart: always
    environment:
      CPS_BACKEND_DB_HOST: clportal_db
      CPS_BACKEND_DB_USER: root 
      CPS_BACKEND_DB_PASSWORD: admin
      CPS_BACKEND_DB_NAME: cloudportaldb
      LMS_HOST: lms
      LMS_PASSWORD: Aa123456
      LMS_PORT: 80
    healthcheck:
      test: ["CMD", "curl", "-X GET", "http://127.0.0.1:8181/cps/api/v1/healthz"] 
      interval: 50s
      timeout: 10s
      retries: 3
    ports:
      - "8181:8181"
volumes:
  lms_db_data: {}
  clportal_db_data: {}
